[package]
name = "orbtk"
version = "0.3.0"
authors = [
    "Florian Blasius <flovanpt@posteo.de>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = "The Orbital Widget Toolkit"
documentation = "https://docs.rs/orbtk"
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]
edition = "2018"

[lib]
name = "orbtk"
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[dependencies]
orbtk-api = { version = "0.1.0", path = "crates/api" }
orbtk-css-engine = { version = "0.1.0", path = "crates/css-engine" }
orbtk-proc-macros = { version = "0.1.0", path = "crates/proc-macros" }
orbtk-render = { version = "0.1.0", path = "crates/render" }
orbtk-shell = { version = "0.1.0", path = "crates/shell" }
orbtk-theme = { version = "0.1.0", path="crates/theme" }
orbtk-utils = { version = "0.1.0", path = "crates/utils" }
orbtk-tree = { version = "0.1.0", path="crates/tree" }
orbtk-widgets = { version = "0.1.0", path="crates/widgets" }
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git" }

[dev-dependencies]
euc = "0.4.2"
vek = "0.9.9"

[features]
debug = ["orbtk-api/debug"]
 
[workspace]
members = [
    "crates/api",
    "crates/css-engine",
    "crates/proc-macros",
    "crates/render",
    "crates/shell",
    "crates/theme",
    "crates/utils",
    "crates/tree",
    "crates/widgets",
]