[package]
name = "orbtk-widgets"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Base OrbTk widget library."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["ui", "widgets"]
edition = "2018"

[dependencies]
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git", branch = "5-multiple-components-of-the-same-type-per-entity"  }
orbtk-api = { version = "0.1.0", path = "../api" }
orbtk-shell = { version = "0.1.0", path = "../shell" }
orbtk-theme = { version = "0.1.0", path = "../theme" }
orbtk-render = { version = "0.1.0", path = "../render" }
orbtk-utils = { version = "0.1.0", path = "../utils" }