[package]
name = "orbtk-api"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "API crate that provides base api and elements for OrbTk like widgets basis."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["ui", "api"]
edition = "2018"

[dependencies]
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git", branch = "5-multiple-components-of-the-same-type-per-entity"  }
orbtk-css-engine = { version = "0.1.0", path = "../css-engine" }
orbtk-render = { version = "0.1.0", path = "../render" }
orbtk-shell = { version = "0.1.0", path = "../shell" }
orbtk-utils = { version = "0.1.0", path = "../utils" }
orbtk-tree = { version = "0.1.0", path= "../tree" }
orbtk-theme = { version = "0.1.0", path= "../theme" }

[features]
debug = []